TASK 014: WORKPLAN IMPLEMENTADO
angtordom1/Acme-Planner pull request #38
Opened 2021-04-21 09:31 UTC by antsansor

He hecho workPlan creo que he definido bien los atributos, en caso de
que den problemas cuando se intente trabajar con ellos se cambian y ya

2021-04-21 19:18 UTC, angtordom1 requested changes
Las dos propiedades derivadas de workplan deben de ser usadas para la sugerencia que es algo que se añadirá al crear una workplan (task que también tienes asignada), aún así "la sugerencia debe empezar el día antes de la task más temprana a las 8:00 y terminar el día después de la última tarea a las 17:00", por lo que se deberían de cambiar ambas propiedades. También se dijo que si no usábamos custom validators mejor porque no es algo que se haya dado en la materia de la asignatura. El validador en sí está bien pero cuando te pongas a trabajar en las operaciones create y update puedes copiar dicho código dentro del validate y borrar el custom validator.

2021-04-22 15:54 UTC, angtordom1 reviewed
No tengo claro si se debería de poner unos atributos para los atributos derivados

2021-04-22 16:24 UTC, felescgon requested changes
Comprueba los comentarios. El principal problema que he encontrado es el tema de workload. Sobre lo que ha dicho Ángel, también podríamos comprobar que atributos se podrán hacer como derivados.

2021-04-22 16:24 UTC, felescgon commented on src/main/java/acme/entities/workPlans/TaskStateConstraint.java
> +	String message() default "En un WorkSpace ninguna Task debe ser privada";
Esto es algo que hay que traducir. Tenemos que encontrar ejemplos en los paquetes de frameworks.
Quería dejar constancia para que no se nos pase. Vería bien verlo este sábado.

2021-04-22 16:24 UTC, felescgon commented on src/main/java/acme/entities/workPlans/WorkPlan.java
> +	}
Este workload debe de pasar por un proceso de formateo. Hay que tener en cuenta que hay que pasarlo a decimal (ya que la parte flotante va desde .0 a .59). Este proceso se puede ver en el administratorDashboardShowService, ahí están todas las funciones necesarias.

2021-04-23 21:15 UTC, angtordom1 approved these changes

2021-04-23 21:16 UTC, angtordom1 approved these changes

2021-04-23 21:32 UTC, felescgon approved these changes
Buen trabajo, bien resuelto.

2021-04-23 21:33 UTC, merged