D03 task 005
angtordom1/Acme-Planner pull request #75
Opened 2021-05-20 14:56 UTC by antsansor

Test de funcionalidades de administrator

2021-05-20 15:12 UTC, angtordom1 requested changes
Deberías de mejorar los comentarios de los tests (mira el documento de este entregable), además , elimina esa línea comentada en AdministratorSpamWordCreateTest (línea 39) si no sirve.

2021-05-22 18:28 UTC, angtordom1 requested changes
Debes de especificar que tipo de fallos son, es decir, que constraints haces que salten.

2021-05-24 09:31 UTC, angtordom1 approved these changes, later dismissed
lgtm

2021-05-24 13:28 UTC, antvinper approved these changes
Todo bien, revisados todos los tests en conjunto y funcionan correctamente.

2021-05-24 13:28 UTC, merged